services:
  web:
    container_name: assistant_web
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: >
      sh -c "python backend/manage.py migrate &&
         python backend/manage.py collectstatic --noinput &&
         gunicorn core.wsgi:application --chdir backend --bind 0.0.0.0:8000"

  db:
    container_name: assistant_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: assistant_bot
      POSTGRES_PASSWORD: AssistantBot2025!#@/-
      POSTGRES_DB: assistant_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    container_name: assistant_redis
    image: redis:7-alpine
    restart: always

  worker:
    container_name: assistant_worker
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery --workdir backend -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
